version: "3.8" # Compose file version
services: # Contains list of all services/containers to deploy
  frontend: 
    depends_on:
      - backend
    networks:
      - store-net
    container_name: "frontend" # Name of the container when deployed
    build: ./frontend # Specify Dockerfile to be built
    image: "frontend" # Name of the image when built
    ports: # Ports
      - "443:80" # Allows port 8080 of the container to be accessible at localhost:80 on your machine
    volumes: # Mounts
      - ./frontend/data:/usr/local/apache2/htdocs/

  backend:
    container_name: "backend"
    networks:
      - store-net
    image: "node" # Image to be used
    working_dir: /home/node/app # Working directory inside the container
    user: "node" # username when logged in
    volumes: # Mounts
      - ./backend/data:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"

networks:
  store-net:
    